### ISSUE TITLE
Peptide bond is not detected

### ISSUE THREAD

**Issue by dargen3** [biotite-dev/hydride#22]
Hello,

I'd like to report a probable bug. I used a structure from the PDB with the code [2JT9](https://www.rcsb.org/structure/2JT9). The hydride version is 1.2.3. When I protonate the structure using hydride (`hydride --infile 2jt9.cif --outfile protonated.cif`), the oxygen and carbon in the peptide bond between ACA7 and ARG8 are protonated incorrectly. It looks as if the double bond between oxygen and carbon is not recognised and therefore hydrogens are added to both atoms.

![image](https://github.com/user-attachments/assets/d30eba17-3d7f-46d0-bf08-bd81f68264fa)

**Comment by padix-key** [comment]
You are quite good in finding structures with edge cases I have not encountered before :+1:. In this case however, I would put the blame on the structure itself:

It was also my first assumption that the peptide bond is not recognized, as `ACA` is actually a separate chain in the structure. But to compensate for that the peptide bond is correctly part of the `struct_conn` catgeory. After further investigation I found the culprit: the oxygen atom. Instead of the `O` atom as used normally in a peptide, the oxygen is named `OXT`. In the 'Chemical Component Dictionary' `OXT` (in contrast to `O`) is only single-bonded, i.e. a hydroxy group. Therefore, the hydrogen atoms at the carbon and the oxygen are actually correct. When you look at your posted image, you see that PyMOL also detects the oxygen as single-bonded hydroxy group. This is also true for `Mol*` (https://www.rcsb.org/3d-view/2JT9).

**Comment by dargen3** [comment]
Thank you! :smile: And thank you for the explanation. It makes sense. It never stops surprising me what everything can go wrong in PDB...
